### ISSUE TITLE
Are you sure this crack jar could generate executable exe file?

### ISSUE THREAD

**Issue by wxb2dyj** [linG5821/Studio3TCrack#3]
I install exe4j and double click studio3t.exe4j, then next and next until happened to following figure:
![1](https://user-images.githubusercontent.com/44050993/53459105-88a9f300-3a73-11e9-82ba-712a479384ec.PNG)
where are these files? You provide nothing.

**Comment by linG5821** [comment]
Open this file, you need to select the relevant jars path, I have to admit, when choosing the path of the jar is not very convenient, because you can only choose one by one, select all dependent jar package, of course, I also uploaded the file, please see https://github.com/linG5821/Studio3TCrack/releases, if you need to build up to date. exe binaries, through the issues, please inform me
